root: ./

redirects:
    readme/metamask-setup: discover/wallets/metamask-setup.md
    readme/wallets: discover/wallets/README.md
    readme/wallets-and-ocean-tokens: discover/wallets-and-ocean.md
    core-concepts: developers/README.md
    core-concepts/architecture: developers/architecture.md
    core-concepts/datanft-and-datatoken: developers/contracts/datanft-and-datatoken.md
    core-concepts/roles: developers/contracts/roles.md
    core-concepts/networks: discover/networks.md
    core-concepts/networks/bridges: discover/networks/bridges.md
    core-concepts/fees: developers/contracts/fees.md
    core-concepts/asset-pricing: developers/contracts/pricing-schemas.md
    core-concepts/did-ddo: developers/identifiers.md
    concepts/ocean-tokens/: discover/basic-concepts.md
    tutorials/wallets-and-ocean-tokens: discover/wallets-and-ocean.md
    using-ocean-market: user-guides/using-ocean-market.md
    using-ocean-market/marketplace-publish-data-asset: user-guides/publish-data-nfts.md
    using-ocean-market/marketplace-download-data-asset: user-guides/buy-data-nfts.md
    using-ocean-market/asset-hosting: user-guides/asset-hosting.md
    using-ocean-market/remove-liquidity-using-etherscan: user-guides/remove-liquidity-pools.md
    building-with-ocean: developers/README.md
    building-with-ocean/build-a-marketplace: developers/build-a-marketplace/README.md
    building-with-ocean/build-a-marketplace/forking-ocean-market: developers/build-a-marketplace/forking-ocean-market.md
    building-with-ocean/build-a-marketplace/customising-your-market: developers/build-a-marketplace/customising-your-market.md
    building-with-ocean/build-a-marketplace/deploying-market: developers/build-a-marketplace/deploying-market.md
    building-with-ocean/using-ocean-libraries: developers/ocean.js/README.md
    building-with-ocean/using-ocean-libraries/configuration: developers/ocean.js/configuration.md
    building-with-ocean/using-ocean-libraries/creating_dataNFT: developers/ocean.js/creating-datanft.md
    building-with-ocean/using-ocean-libraries/create-datatoken-with-fixed-pricing: developers/ocean.js/publish.md
    building-with-ocean/using-ocean-libraries/mint-datatoken: developers/ocean.js/mint-datatoken.md
    building-with-ocean/using-ocean-libraries/update-metadata: developers/ocean.js/update-metadata.md
    building-with-ocean/compute-to-data: developers/compute-to-data/README.md
    building-with-ocean/compute-to-data/compute-to-data-architecture: developers/compute-to-data/compute-to-data-architecture.md
    building-with-ocean/compute-to-data/compute-to-data-datasets-algorithms: developers/compute-to-data/compute-to-data-datasets-algorithms.md
    building-with-ocean/compute-to-data/compute-to-data-algorithms: developers/compute-to-data/compute-to-data-algorithms.md
    building-with-ocean/compute-to-data/compute-to-data-minikube: infrastructure/compute-to-data-minikube.md
    building-with-ocean/compute-to-data/compute-to-data-docker-registry: infrastructure/compute-to-data-docker-registry.md
    building-with-ocean/compute-to-data/user-defined-parameters: developers/compute-to-data/compute-options.md
    building-with-ocean/deploying-components: infrastructure/README.md
    building-with-ocean/deploying-components/setup-server: infrastructure/setup-server.md
    building-with-ocean/deploying-components/deploying-ocean-subgraph: infrastructure/deploying-ocean-subgraph.md
    building-with-ocean/deploying-components/deploying-marketplace: infrastructure/deploying-marketplace.md
    building-with-ocean/deploying-components/deploying-aquarius: infrastructure/deploying-aquarius.md
    building-with-ocean/deploying-components/deploying-provider: infrastructure/deploying-provider.md
    building-with-ocean/using-ocean-subgraph: developers/subgraph/README.md
    building-with-ocean/using-ocean-subgraph/list-data-nfts: developers/subgraph/list-data-nfts.md
    building-with-ocean/using-ocean-subgraph/list-datatokens: developers/subgraph/list-datatokens.md
    building-with-ocean/using-ocean-subgraph/get-data-nft-information: developers/subgraph/get-data-nft-information.md
    building-with-ocean/using-ocean-subgraph/get-datatoken-information: developers/subgraph/get-datatoken-information.md
    building-with-ocean/using-ocean-subgraph/list-fixed-rate-exchanges: developers/subgraph/list-fixed-rate-exchanges.md
    building-with-ocean/using-ocean-subgraph/deploying-ocean-subgraph: infrastructure/deploying-components/deploying-ocean-subgraph.md
    building-with-ocean/contributing: contribute/README.md
    building-with-ocean/contributing/code-of-conduct: contribute/code-of-conduct.md
    building-with-ocean/contributing/legal-reqs: contribute/legal-reqs.md
    building-with-ocean/projects-using-ocean: contribute/projects-using-ocean.md
    veocean-data-farming: rewards/README.md
    veocean-data-farming/veocean: rewards/df-veocean.md
    veocean-data-farming/df-intro: rewards/df-intro.md
    veocean-data-farming/df-background: rewards/df-volumedf.md
    veocean-data-farming/emissions-apys: rewards/df-emissions-apys.md
    veocean-data-farming/delegation: rewards/README.md
    veocean-data-farming/veocean-data-farming-tutorial: rewards/user-guides/how-to-veocean.md
    rewards/veOcean-Data-Farming-Tutorial: rewards/user-guides/how-to-veocean.md
    api-references: developers/README.md
    api-references/aquarius-rest-api: developers/aquarius/asset-requests.md
    api-references/provider-rest-api: developers/provider/general-endpoints.md
    user-guides/claim-ocean-rewards: rewards/user-guides/how-to-claim-rewards.md
    user-guides/get-started-df: rewards/user-guides/how-to-veocean.md
    user-guides/how-to-veocean: rewards/user-guides/how-to-veocean.md
    user-guides/how-to-claim-rewards: rewards/user-guides/how-to-claim-rewards.md
    user-guides/how-to-data-farm: rewards/user-guides/how-to-volumedf.md
    user-guides/data-farming/how-to-volume-df: rewards/user-guides/how-to-volumedf.md
    user-guides/data-farming/how-to-df-estimate-apy: rewards/user-guides/how-to-estimate-apy.md
    user-guides/data-farming/how-to-estimate-apy: rewards/user-guides/how-to-estimate-apy.md
    user-guides/data-farming/how-to-challengedf: rewards/user-guides/how-to-challengedf.md
    user-guides/data-farming/how-to-delegate: rewards/user-guides/how-to-delegate.md
    user-guides/data-farming/README: rewards/user-guides/README.md
    rewards/df-basic: rewards/df-guides.md
    rewards/veocean: rewards/df-veocean.md
    rewards/df-max-out-yield: rewards/df-volumedf.md
    rewards/df-guides.md: rewards/user-guides/README.md