root: ./

redirects:
    readme/metamask-setup: discover/wallets/metamask-setup.md
    readme/wallets: discover/wallets/README.md
    readme/wallets-and-ocean-tokens: discover/wallets-and-ocean.md
    core-concepts: developers/README.md
    core-concepts/architecture: developers/architecture.md
    core-concepts/datanft-and-datatoken: developers/contracts/datanft-and-datatoken.md
    core-concepts/roles: developers/contracts/roles.md
    core-concepts/networks: discover/networks.md
    core-concepts/networks/bridges: discover/networks/bridges.md
    core-concepts/fees: developers/contracts/fees.md
    core-concepts/asset-pricing: developers/contracts/pricing-schemas.md
    core-concepts/did-ddo: developers/identifiers.md
    concepts/ocean-tokens/: discover/basic-concepts.md
    tutorials/wallets-and-ocean-tokens: discover/wallets-and-ocean.md
    using-ocean-market: user-guides/using-ocean-market.md
    using-ocean-market/marketplace-publish-data-asset: user-guides/publish-data-nfts.md
    using-ocean-market/marketplace-download-data-asset: user-guides/buy-data-nfts.md
    using-ocean-market/asset-hosting: user-guides/asset-hosting.md
    using-ocean-market/remove-liquidity-using-etherscan: user-guides/remove-liquidity-pools.md
    building-with-ocean: developers/README.md
    building-with-ocean/build-a-marketplace: developers/build-a-marketplace/README.md
    building-with-ocean/build-a-marketplace/forking-ocean-market: developers/build-a-marketplace/forking-ocean-market.md
    building-with-ocean/build-a-marketplace/customising-your-market: developers/build-a-marketplace/customising-your-market.md
    building-with-ocean/build-a-marketplace/deploying-market: developers/build-a-marketplace/deploying-market.md
    building-with-ocean/using-ocean-libraries: developers/ocean.js/README.md
    building-with-ocean/using-ocean-libraries/configuration: developers/ocean.js/configuration.md
    building-with-ocean/using-ocean-libraries/creating_dataNFT: developers/ocean.js/creating-datanft.md
    building-with-ocean/using-ocean-libraries/create-datatoken-with-fixed-pricing: developers/ocean.js/publish.md
    building-with-ocean/using-ocean-libraries/mint-datatoken: developers/ocean.js/mint-datatoken.md
    building-with-ocean/using-ocean-libraries/update-metadata: developers/ocean.js/update-metadata.md
    building-with-ocean/compute-to-data: developers/compute-to-data/README.md
    building-with-ocean/compute-to-data/compute-to-data-architecture: developers/compute-to-data/compute-to-data-architecture.md
    building-with-ocean/compute-to-data/compute-to-data-datasets-algorithms: developers/compute-to-data/compute-to-data-datasets-algorithms.md
    building-with-ocean/compute-to-data/compute-to-data-algorithms: developers/compute-to-data/compute-to-data-algorithms.md
    building-with-ocean/compute-to-data/compute-to-data-minikube: infrastructure/compute-to-data-minikube.md
    building-with-ocean/compute-to-data/compute-to-data-docker-registry: infrastructure/compute-to-data-docker-registry.md
    building-with-ocean/compute-to-data/user-defined-parameters: developers/compute-to-data/compute-options.md
    building-with-ocean/deploying-components: infrastructure/README.md
    building-with-ocean/deploying-components/setup-server: infrastructure/setup-server.md
    building-with-ocean/deploying-components/deploying-ocean-subgraph: infrastructure/deploying-ocean-subgraph.md
    building-with-ocean/deploying-components/deploying-marketplace: infrastructure/deploying-marketplace.md
    building-with-ocean/deploying-components/deploying-aquarius: infrastructure/deploying-aquarius.md
    building-with-ocean/deploying-components/deploying-provider: infrastructure/deploying-provider.md
    building-with-ocean/using-ocean-subgraph: developers/subgraph/README.md
    building-with-ocean/using-ocean-subgraph/list-data-nfts: developers/subgraph/list-data-nfts.md
    building-with-ocean/using-ocean-subgraph/list-datatokens: developers/subgraph/list-datatokens.md
    building-with-ocean/using-ocean-subgraph/get-data-nft-information: developers/subgraph/get-data-nft-information.md
    building-with-ocean/using-ocean-subgraph/get-datatoken-information: developers/subgraph/get-datatoken-information.md
    building-with-ocean/using-ocean-subgraph/list-fixed-rate-exchanges: developers/subgraph/list-fixed-rate-exchanges.md
    building-with-ocean/using-ocean-subgraph/deploying-ocean-subgraph: infrastructure/deploying-components/deploying-ocean-subgraph.md
    building-with-ocean/contributing: contribute/README.md
    building-with-ocean/contributing/code-of-conduct: contribute/code-of-conduct.md
    building-with-ocean/contributing/legal-reqs: contribute/legal-reqs.md
    building-with-ocean/projects-using-ocean: contribute/projects-using-ocean.md
    user-guides/join-a-data-challenge: data-scientists/join-a-data-challenge.md
    user-guides/sponsor-a-data-challenge: data-scientists/sponsor-a-data-challenge.md
    data-science/: data-scientists/README.md
    data-science/data-engineers: data-scientists/README.md
    data-science/join-a-data-challenge: data-scientists/join-a-data-challenge.md
    data-science/sponsor-a-data-challenge: data-scientists/sponsor-a-data-challenge.md
    data-science/the-data-value-creation-loop: data-scientists/the-data-value-creation-loop.md
    data-science/ocean.py/: data-scientists/ocean.py/README.md
    data-science/ocean.py/compute-flow: data-scientists/ocean.py/compute-flow.md
    data-science/ocean.py/consume-flow: data-scientists/ocean.py/consume-flow.md
    data-science/ocean.py/datatoken-interface-tech-details: data-scientists/ocean.py/datatoken-interface-tech-details.md
    data-science/ocean.py/install: data-scientists/ocean.py/install.md
    data-science/ocean.py/local-setup: data-scientists/ocean.py/local-setup.md
    data-science/ocean.py/ocean-assets-tech-details: data-scientists/ocean.py/ocean-assets-tech-details.md
    data-science/ocean.py/ocean-compute-tech-details: data-scientists/ocean.py/ocean-compute-tech-details.md
    data-science/ocean.py/publish-flow: data-scientists/ocean.py/publish-flow.md
    data-science/ocean.py/remote-setup: data-scientists/ocean.py/remote-setup.md
    data-science/ocean.py/technical-details: data-scientists/ocean.py/technical-details.md
    "developers/ocean.py": data-scientists/ocean.py/README.md
    developers/ocean.py/compute-flow: data-scientists/ocean.py/compute-flow.md
    developers/ocean.py/consume-flow: data-scientists/ocean.py/consume-flow.md
    developers/ocean.py/datatoken-interface-tech-details: data-scientists/ocean.py/datatoken-interface-tech-details.md
    developers/ocean.py/install: data-scientists/ocean.py/install.md
    developers/ocean.py/local-setup: data-scientists/ocean.py/local-setup.md
    developers/ocean.py/ocean-assets-tech-details: data-scientists/ocean.py/ocean-assets-tech-details.md
    developers/ocean.py/ocean-compute-tech-details: data-scientists/ocean.py/ocean-compute-tech-details.md
    developers/ocean.py/publish-flow: data-scientists/ocean.py/publish-flow.md
    developers/ocean.py/remote-setup: data-scientists/ocean.py/remote-setup.md
    developers/ocean.py/technical-details: data-scientists/ocean.py/technical-details.md
    api-references: developers/README.md
    api-references/aquarius-rest-api: developers/aquarius/asset-requests.md
    api-references/provider-rest-api: developers/provider/general-endpoints.md
    veocean-data-farming: data-farming/README.md
    veocean-data-farming/veocean: data-farming/README.md
    veocean-data-farming/df-intro: data-farming/README.md
    veocean-data-farming/df-background: data-farming/README.md
    veocean-data-farming/emissions-apys: data-farming/README.md
    veocean-data-farming/delegation: data-farming/README.md
    veocean-data-farming/veocean-data-farming-tutorial: data-farming/README.md
    user-guides/claim-ocean-rewards: data-farming/README.md
    user-guides/get-started-df: data-farming/README.md
    user-guides/how-to-veocean: data-farming/README.md
    user-guides/how-to-claim-rewards: data-farming/README.md
    user-guides/how-to-data-farm: data-farming/README.md
    user-guides/data-farming/how-to-volume-df: data-farming/README.md
    user-guides/data-farming/how-to-df-estimate-apy: data-farming/README.md
    user-guides/data-farming/how-to-estimate-apy: data-farming/README.md
    user-guides/data-farming/how-to-challengedf: data-farming/README.md
    user-guides/data-farming/how-to-delegate: data-farming/README.md
    user-guides/rewards/: data-farming/README.md
    rewards/: data-farming/README.md
    rewards/veOcean-Data-Farming-Tutorial: data-farming/README.md
    rewards/df-basic: data-farming/README.md
    rewards/veocean: data-farming/README.md
    rewards/df-max-out-yield: data-farming/README.md
    rewards/df-guides: data-farming/README.md
    rewards/df-challengedf: data-farming/README.md
    rewards/df-emissions-apys: data-farming/README.md
    rewards/df-faq: data-farming/README.md
    rewards/df-intro: data-farming/README.md
    rewards/df-veocean: data-farming/README.md
    rewards/df-volumedf: data-farming/README.md
    rewards/user-guides/: data-farming/README.md
    rewards/user-guides/how-to-challengedf: data-farming/README.md
    rewards/user-guides/how-to-claim-rewards: data-farming/README.md
    rewards/user-guides/how-to-delegate: data-farming/README.md
    rewards/user-guides/how-to-estimate-apy: data-farming/README.md
    rewards/user-guides/how-to-veocean: data-farming/README.md
    rewards/user-guides/how-to-volumedf: data-farming/README.md
    data-farming/challengedf.md: data-farming/README.md
    data-farming/challengedf-guide.md: data-farming/README.md